### ISSUE TITLE
No video stream (PiCamera 3)

### ISSUE THREAD

**Issue by Grynr38** [mgrl/photobooth-app#57]
Hi,
Thanks a lot for this project !
I've been trying to make it work with Camera v3 but no luck: it streams the default app's yellow background and not the camera's image.
The camera works fine on the pi (with libcamera)...
Any advise / help would be greatly appreciated.

Thanks again !

**Comment by mgrl** [comment]
Did you go to admin config tab backends and chose picamera as main backend? That should be it

**Comment by mgrl** [comment]
You are probably right the app needs more and better description.

**Comment by Grynr38** [comment]
Amazing work by the way !
And thanks so much for your app.

**Comment by mgrl** [comment]
Glad it works for you! Pictures how your booth looks like are very welcome :)

**Comment by mgrl** [comment]
Added description in the docs: https://mgrl.github.io/photobooth-docs/setup/#raspberry-csi-camera-modules
