### ISSUE TITLE
Outdated link on admin page ( troubleshooting guide ) 

### ISSUE THREAD

**Issue by dtimes** [mgrl/photobooth-app#84]
Hi, 

the link link on http://$IP:8000/#/admin/help   "troubleshooting guide" points to https://mgrl.github.io/photobooth-docs/help/troubleshooting/  which seems to be a broken/outdated version of https://mgrl.github.io/photobooth-docs/support/troubleshooting/

might be good do adjust this ? 

again thanks for the work you are putting into this software

**Comment by mgrl** [comment]
Thank you for the report.
Maybe I can add some automatic link checking at a later point.
It's fixed in the next release.
